name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '52 18 * * 2'

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout self
      uses: actions/checkout@v4
    - name: Checkout scratch-gui
      uses: actions/checkout@v4
      with:
        repository: TurboWarp/scratch-gui
        path: scratch-gui
    - name: Build
      run: |
        cd scratch-gui
        npm ci
        NODE_ENV=production ROUTING_STYLE=hash npm run build
    - name: Patch
      run: python3 patch.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: tw-standalone.zip
        path: ./scratch-gui/build/
  
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        delete_release: true
        tag_name: build
        github_token: ${{ github.token }}
    - name: Release
      uses: softprops/action-gh-release@v2.0.9
      with:
        name: Build
        tag_name: build
        files: |
          */*
        make_latest: true
        fail_on_unmatched_files: true
