name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '52 18 * * 2'

permissions:
  contents: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
      with:
        node-version: 20
    - name: Checkout self
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Checkout scratch-gui
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: TurboWarp/scratch-gui
        path: scratch-gui
    - name: Checkout extensions
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        repository: TurboWarp/extensions
        path: extensions
    - name: Build GUI
      run: |
        cd scratch-gui
        npm ci
        NODE_ENV=production ROUTING_STYLE=hash npm run build
        cd ..
    - name: Build extensions
      run: |
        cd extensions
        npm ci
        NODE_ENV=production npm run build
        cd ..
    - name: Patch
      run: python3 patch.py
    - name: Bundle into single file
      run: |
        node patch_singlefile.mjs
        node patch_singlefile.mjs --extensions
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tw-standalone
        path: tw-standalone.html
    - name: Upload extensions artifact
      uses: actions/upload-artifact@v4
      with:
        name: tw-standalone-offline-extensions
        path: tw-standalone-offline-extensions.html
  
  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        delete_release: true
        tag_name: build
        github_token: ${{ github.token }}
    - name: Release
      uses: softprops/action-gh-release@v2.0.9
      with:
        name: Standalone TurboWarp Build
        tag_name: build
        body: |
          Download the `tw-standalone.html` file below and open it in your browser to use TurboWarp.
          Still very experimental, not all things will work properly.
          By default, unsandboxed TurboWarp extensions are still fetched from extensions.turbowarp.org. Use `tw-standalone-offline-extensions.html` instead for the extensions themselves to work offline, but documentation pages, extension example files, sample projects and the standalone library page (not the one in the editor) will still only be online.
        files: "*.*"
        make_latest: true
        fail_on_unmatched_files: true
